### ISSUE TITLE
Figure out data model

### ISSUE THREAD

**Issue by sofita** [insightorchards/calendar-ui#10]
### Business Context
We need to model the data that users will be saving

### Notes
Collaborate with leads to discuss and determine data model. 
Create schema for basic entities of app.

### Acceptance Criteria
Given I am a dev on project
When I look at the schema
Then I see how the project entities are modelled

**Comment by elliedori** [comment]
Data model can be viewed here: https://nextcloud.insightorchards.com/apps/onlyoffice/s/r5pq3wpwEyRmD4M?fileId=98737
