### ISSUE TITLE
Connect creation of event to backend and DB

### ISSUE THREAD

**Issue by sofita** [insightorchards/calendar-ui#11]
### Business Context
We need users to be able to persist their data in the app. 

### Notes
Connect the frontend to the backend for the entry creation flow. Connect backend to database. 

### Acceptance Criteria
Given I am a user on the creation page of the UI
When I create an entry
Then that data is in the database.

**Comment by angepol** [comment]
Baby steps

1. Add a create entry endpoint 
2. Create a post request with event details to DB
3. Test flow from UI
