### ISSUE TITLE
Build out ability to delete calendar entries

### ISSUE THREAD

**Issue by elliedori** [insightorchards/calendar-ui#23]
### Business Context
We need users to be able to be able to delete calendar entries.

### Notes
Build out the ability to delete entries across front and backend. Make sure to use the `DELETE` HTTP verb when building out the backend to ensure this endpoint is RESTful.

### Acceptance Criteria
Given I am a user with a calendar entry
When I delete the entry via the UI
Then it is deleted from the DB and no longer shows up in the UI

**Comment by angepol** [comment]
Baby Step

1. Create DELETE entry endpoint & test
