### ISSUE TITLE
Figure out how to deploy api

### ISSUE THREAD

**Issue by sofita** [insightorchards/calendar-ui#32]
## Context
In order for external clients (ie LoveLoom) to be able to connect. This is something we should do sooner rather than later because it can be tricky with roadbumps and gotchas. 

## AC
API is available at a non-local url that we can curl to make requests. 
Developer(s) can chose platform that is most suitable for us.

**Comment by Ashlynn223** [comment]
We'll be integrating into the loveloom API instead
