### ISSUE TITLE
Add `notes` input field to create entry form

### ISSUE THREAD

**Issue by sofita** [insightorchards/calendar-ui#43]
### Business Context
We need users to be able to add `notes` to their calendar entry

### Notes
- Build out the ability to add a `notes` section
- update schema to reflect name change from `description` to `notes`

### Acceptance Criteria
Given user is making a entry
When they fill out a notes section
Then they see it when they click on the created event

**Comment by Jake-Mitchell** [comment]
Update: We decided to implement this using "description" as the name instead of "notes" for now, but we are open to a later team discussion on it if anyone wants to share their thought process on their preference and feelings for a "notes" rename.

**Comment by Jake-Mitchell** [comment]
We found out that Google Calendar seemed to use "description" as it's default, but Apple's Calendar used "notes"
<img width="860" alt="Screen Shot 2022-11-27 at 3 38 40 PM" src="https://user-images.githubusercontent.com/39348241/204165924-cebfc18b-f42f-45f7-9191-e29ff8480ff5.png">
