### ISSUE TITLE
Handle API errors on the frontend

### ISSUE THREAD

**Issue by sofita** [insightorchards/calendar-ui#53]
### Business Context
We need users to be able to see when there is an error.

### Notes
Build out error handling on the frontend (hooks) to catch API errors and display a message to users in the UI

### Acceptance Criteria
Given an API endpoint returns an error status code
When the hook that calls that endpoint is used on a frontend component
Then the error is handled and a message to user is displayed

**Comment by elliedori** [comment]
branch: cal-53-fe-error-handling
