### ISSUE TITLE
Implement interactive calendar

### ISSUE THREAD

**Issue by elliedori** [insightorchards/calendar-ui#64]
Business Context
We want interactive calendar event creation.

Notes
Use the research branch and continue working on showing the form on date click, with date pre-selected.

Acceptance Criteria
Given I am a user on the calendar app
When I click a date square
Then the form pops up with the start date matching the date I clicked

**Comment by Ashlynn223** [comment]
Note - This work will be in addition to the above criteria:

Given I am a user on the calendar app
When I click "create event" button on the left side panel
Then I see a modal show up with a form to create an event and the date inputs pre-filled to be the current date

**Comment by angepol** [comment]
branch name: cal-62-interactive-calendar
